### ISSUE TITLE
ModuleNotFoundError: No module named 'core'

### ISSUE THREAD

**Issue by americanhanko** [filipp/py-gsxws#11]
Attempting to install gsxws on Python 3.6.1

```Collecting gsxws
  Using cached gsxws-0.92.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7w/yzqmnn5128gf_ww4zg7mz07w0000gp/T/pip-build-igjg_spt/gsxws/setup.py", line 2, in <module>
        from gsxws.core import VERSION
      File "/private/var/folders/7w/yzqmnn5128gf_ww4zg7mz07w0000gp/T/pip-build-igjg_spt/gsxws/gsxws/__init__.py", line 1, in <module>
        from core import *
    ModuleNotFoundError: No module named 'core'
```

**Comment by americanhanko** [comment]
- Fixed it by changing the contents of `gsxws/__init__.py` to `from gsxws import *`
- Also had to adjust line 37 in `objectify.py` to `from gsxws import objectify`
