### ISSUE TITLE
Mismatched Tag

### ISSUE THREAD

**Issue by justinessert** [filipp/py-gsxws#12]
Each time I try to connect to gsx I am getting an mismatched tag error. Could you let me know what I could fix here?
```
>>> import os
>>> import gsxws
>>> os.environ['GSX_CERT'] = 'cert.pem'
>>> os.environ['GSX_KEY'] = 'key.pem'
>>> gsxws.connect(USERNAME,SOLDTO) 
Enter PEM pass phrase:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/justin/anaconda3/lib/python2.7/site-packages/gsxws/core.py", line 544, in connect
    return act.login()
  File "/Users/justin/anaconda3/lib/python2.7/site-packages/gsxws/core.py", line 512, in login
    result = self._req._submit("Authenticate")
  File "/Users/justin/anaconda3/lib/python2.7/site-packages/gsxws/core.py", line 335, in _submit
    raise GsxError(xml=xml, url=self._url)
  File "/Users/justin/anaconda3/lib/python2.7/site-packages/gsxws/core.py", line 170, in __init__
    root = ET.fromstring(xml)
  File "/Users/justin/anaconda3/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/Users/justin/anaconda3/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/Users/justin/anaconda3/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 7, column 2
```

**Comment by filipp** [comment]
Could you show the XML that you get back form GSX?


Thanks,
-filipp

**Comment by justinessert** [comment]
I'm not sure how to retrieve the XML document from the error, could you provide me with some insight as to how to find it?

**Comment by jholt13** [comment]
I noticed the same issue when using the prebuilt version in pip.  If I installed from pip using the latest github source everything went smoothly.
