### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by chasetb** [filipp/py-gsxws#3]
I tried running the test on the ReadMe file from a Django shell and I keep getting this error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/sal_env/sal/gsxws/core.py", line 504, in connect
    return act.login()
  File "/usr/local/sal_env/sal/gsxws/core.py", line 472, in login
    result = self._req._submit("Authenticate")
  File "/usr/local/sal_env/sal/gsxws/core.py", line 325, in _submit
    raise GsxError(xml=xml, url=self._url)
GsxError: Your request cannot be processed at this time. Please try again later. If this message persists, please contact GSX support via the help function.
```

**Comment by filipp** [comment]
Hmm, looks like a temp GSX issue. Is it working now?

**Comment by chasetb** [comment]
Yes, it is. I'm now getting the same error as #2 however.
